### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by Asw-S93** [allartprotocol/unity-solana-demo#1]
Steps to have this setup for production would be much appreciated. Especially for newbie NFT developers like myself, thanks!

**Comment by ren-salazar-ps** [comment]
I second the motion. :) Please add some documentation (even if it's a short one, it would greatly help).

**Comment by vuckovic95** [comment]
You have detailed instructions on how to import a wallet into a project at the following link : https://github.com/allartprotocol/unity-solana-wallet
