### ISSUE TITLE
Errors just after import !

### ISSUE THREAD

**Issue by MaciejProkopowicz** [allartprotocol/unity-solana-demo#2]
![image](https://user-images.githubusercontent.com/84624801/151848300-2c68c79a-1160-46a4-9b7d-2c793e3a618e.png)

Is this still working as I just wanted to test it out and have dependecies error. My unity is latest version 2020.3.26f1.
Let me know if you have any clue. Thx !

**Comment by vuckovic95** [comment]
You have to import wallet package. You have detailed instructions on how to import a wallet into a project at the following link : https://github.com/allartprotocol/unity-solana-wallet
