### ISSUE TITLE
Impossible to use demo with Windows native exectuable or WebGl build

### ISSUE THREAD

**Issue by pgibouin** [allartprotocol/unity-solana-demo#3]
Hi,

I have tried to work on the demo. It's very difficult because there is no explication. First, for the demo to work, you need to get back the seed phrase written in comment in the LoginScreen.cs file and restore the wallet from it. But even with the wallet connected and subscribed "green", it's impossible to get to the main screen if the demo has been compiled in native Windows executable or WebGL build. 

It only works in Unity developer mode with the internal player. It won't work with any compilated builds.  Exactly as the demo in this video. Can you please check what may be the problem ? Thank you

Pierre

**Comment by vuckovic95** [comment]
Please read documentation here https://github.com/allartprotocol/unity-solana-wallet. 
Write if you still having problems.
